"""Fix user, order, order_item, shipping_rule

Revision ID: 8d2f06b1ab87
Revises: cf981ea4a0ab
Create Date: 2025-09-17 14:40:11.389142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2f06b1ab87'
down_revision: Union[str, Sequence[str], None] = 'cf981ea4a0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_method', sa.String(length=50), nullable=False))
    op.alter_column('shipping_rules', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('shipping_rules_id_seq'::regclass)"))
    op.drop_column('users', 'middle_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middle_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('shipping_rules', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('shipping_rules_id_seq'::regclass)"))
    op.drop_column('orders', 'delivery_method')
    # ### end Alembic commands ###
