"""Update orders, order_items and payments table

Revision ID: c6851ab1b14a
Revises: 0965417cd7d4
Create Date: 2025-09-25 13:23:14.310411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6851ab1b14a'
down_revision: Union[str, Sequence[str], None] = '0965417cd7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shipping_last_name', sa.String(length=50), nullable=False),
    sa.Column('shipping_first_name', sa.String(length=50), nullable=False),
    sa.Column('shipping_address_line1', sa.String(length=100), nullable=False),
    sa.Column('shipping_address_line2', sa.String(length=100), nullable=True),
    sa.Column('shipping_city', sa.String(length=50), nullable=False),
    sa.Column('shipping_state', sa.String(length=50), nullable=False),
    sa.Column('shipping_zip', sa.String(length=10), nullable=False),
    sa.Column('shipping_phone_number', sa.String(length=15), nullable=False),
    sa.Column('subtotal_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('shipping_fee', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('payment_processing_fee', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('shipping_method', sa.String(length=50), nullable=False),
    sa.Column('order_status', sa.Enum('created', 'confirmed', 'paid', 'shipped', 'delivered', 'cancelled', 'returned', name='orderstatusenum'), nullable=False),
    sa.Column('shipping_status', sa.Enum('not_required', 'unshipped', 'preparing', 'shipped', 'delivered', 'returned', 'cancelled', name='shippingstatusenum'), nullable=False),
    sa.Column('payment_status', sa.Enum('unpaid', 'pending', 'paid', 'failed', 'refunded', 'cancelled', name='paymentstatusenum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.Enum('unpaid', 'pending', 'paid', 'failed', 'refunded', 'cancelled', name='paymentstatusenum'), nullable=False),
    sa.Column('transaction_token', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('item_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('item_total_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_sku_id'), 'order_items', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_sku_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
