"""create AdminUser table

Revision ID: ec6db21616d4
Revises: c6851ab1b14a
Create Date: 2025-10-14 13:55:28.576597

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "ec6db21616d4"
down_revision: Union[str, Sequence[str], None] = "c6851ab1b14a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
